---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
 
  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml 
    copy:
      src: ../files/filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module ; setup filebeat ; start service
    command: sudo filebeat modules enable system 
    
  - name: setup filebeat
    command: sudo filebeat setup 
    
  - name: start filebeat
    command: sudo service filebeat start

  
